### ISSUE TITLE
o mirror é muito bom

### ISSUE THREAD

**Issue by rictom** [jonathands/dados-abertos-receita-cnpj#2]
Oi @jonathands, legal que você criou esse mirror das bases de cnpj. Não sabia que dava para aproveitar o github para isso. Eu tinha apagado  os arquivos de um mês passado sem querer e pelo seu link deu para baixar super rápido. Obrigado!

**Comment by jonathands** [comment]
@rictom eu também me surpreendi que funcionou hehehe, mas enquanto o github mantiver ativo vou atualizar
